### PR TITLE
moved txt file into names folder

### PR DESCRIPTION
**Pull request by daguito81**
move ashleyo.txt to the names folder

### CODE REVIEW

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
Beware! I still see the original here https://github.com/daguito81/ie-mbd-advanced-python/blob/cleanup/ashleyo.txt

**Comment by daguito81** [comment]
Ill fix it and redo it

**Comment by daguito81** [comment]
should be fine now

**Review by astrojuanlu — APPROVED** [review]
:ok_hand:

**Pull request merged**
