### PR TITLE
New branch2

### PR DESCRIPTION
**Pull request by ScottPanIE**
Dear Professor, please check if the name and email appear properly now.

### CODE REVIEW

**Review by astrojuanlu — CHANGES_REQUESTED** [review]
Sorry for picking on you, but we are not done yet! I will use the :hamburger: technique:

* *Good news:* Your commits are now attributed correctly, and if you configured your system properly, all the future commits will be, as well.
* *Bad news:* You have a git mess!
* *Good news:* It happens to everybody. And we can fix it!

If you go here:

https://github.com/Juanlu001/ie-mbd-advanced-python/network

You will notice this:

Screenshot_2019-03-29 Juanlu001 ie-mbd-advanced-python

Thew `new-branch2` departs from the middle of `new-branch`! That's why you have both attributed and unattributed commits:

https://github.com/Juanlu001/ie-mbd-advanced-python/pull/10/commits

To fix this, you only need to do:

```
$ git checkout new-branch2  # just in case you were not here already
$ git rebase origin/master
$ git push --force  # to _override_ the history
```

And it should work! If any operation fails for you, post the output as a comment in this pull request and I will help.

**Comment by ScottPanIE** [comment]
Dear Professor,

I followed the step as you have provided, after I run `git push --force` I get the following error:

fatal: The current branch new-branch2 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin new-branch2

And if I run `git push --set-upstream origin new-branch2`, it doesn't give me permission. Is there any step I missed or shall I merge my two branches into one?

**Comment by astrojuanlu** [comment]
You almost have it - `origin` is, most likely, _my_ repository, so first check that

```
$ git remote
```

displays `origin` (mine) and a second one (yours, say, `ScottPanIE`). Then, you would have to do

```
$ git push --set-upstream ScottPanIE new-branch-2
```

**Comment by ScottPanIE** [comment]
I did `git remote` and found out there are two one is ScottPanIE, and the another one is origin. So I did this: `git push --set-upstream ScottPanIE new-branch2`, 
and it returns: `Branch 'new-branch2' set up to track remote branch 'new-branch2' from 'ScottPanIE'.`
then I ran `git rebase ScottPanIE/new-branch2`
then I ran `git push --force`
it returns: `Everything up-to-date`

not sure if this has fixed the issue, please double check

**Comment by astrojuanlu** [comment]
Just one change: you did `git rebase ScottPanIE/new-branch2`, but it should be `git rebase origin/master` instead, to specify that you want to move `new-branch2` on top of `origin/master`. Then `git push --force` should do the rest.

**Comment by ScottPanIE** [comment]
I tried the following:
```
git push --set-upstream ScottPanIE new-branch2
git rebase origin/master
git push --force
```
But it doesn't seem to make any change in the network of the branches.
Do you mean `git rebase --onto origin/master ScottPanIE/new-branch2`?

**Comment by ScottPanIE** [comment]
Also I tried to delete or merge my two branches, but it doesn't fix the issue

**Comment by daguito81** [comment]
@Juanlu001 seeing his repo as remote I can see:
image

seems like new-branch is a branch of new-branch 2. Couldn't he delete new-branch with git branch -D new-branch and just merge new-branch2 ?

**Comment by ScottPanIE** [comment]
> @Juanlu001 seeing his repo as remote I can see:
> image
> 
> seems like new-branch is a branch of new-branch 2. Couldn't he delete new-branch with git branch -D new-branch and just merge new-branch2 ?

Also I made a mistake, I shouldn't create my new-branch2 based on the previous new-branch.

**Comment by astrojuanlu** [comment]
Gosh, you're right - I was missing that we need [a three-way rebase](https://stackoverflow.com/a/29916361/554319) (`git rebase --onto <newparent> <oldparent>`):

```
$ git rebase --onto origin/master 0e9c670a78
```

0e9c670a78 is the commit where `new-branch2` starts.

**Comment by ScottPanIE** [comment]
it seems that now my two branches have been merged into one

**Comment by astrojuanlu** [comment]
Correct - Although you did the rebase correctly! Now, let's "step back" to make the `new-branch2` contain only the commit we want:

```
$ git checkout new-branch2
$ git reset --hard 2d4368a3180f9eccc282d440feb7120008c08b7c
$ git push --force
```

**Comment by daguito81** [comment]
I understand the educational purpose of doing the rebase. But in a real scenario, as soon as the double branch mess happened. Considering we only had to create a simple file  would we have prefered to do git reset? or simply delete the repo and reclone it ? @Juanlu001

**Comment by astrojuanlu** [comment]
@ScottPanIE worked! :tada:

> I understand the educational purpose of doing the rebase. But in a real scenario, as soon as the double branch mess happened. Considering we only had to create a simple file would we have prefered to do git reset? or simply delete the repo and reclone it ?

It's only for its educational value, really - also, I think it is useful to face these kind of situations, because they happen _all the time_. I lost count of the times I have had to go through explanations similar to this one here.

It took a bit of effort and back-and-forth, but I hope by registering our thought process and be patient enough to not start from scratch has value for those learning :slightly_smiling_face:

**Comment by astrojuanlu** [comment]
:warning: Next steps :warning: 

Your pull request has been merged to `master`. That means that, if you don't do anything, your local `master` and `ScottPanIE/master` are outdated with respect to `origin/master`. On the other hand, you should avoid working on this branch anymore in the future.

To put yourself in a clean state again, you have to:

1. Click "remove branch" here in this pull request (don't click "remove fork"!)
2. `git checkout master`
3. `git fetch origin` (assuming https://github.com/Juanlu001/ie-mbd-advanced-python/ is `origin` for you)
4. `git merge --ff-only origin master` (this will update your local `master` with `origin/master`, and fail if you accidentally made any commit in `master`)
5. `git fetch -p ScottPanIE` (assuming https://github.com/ScottPanIE/ie-mbd-advanced-python/ is `ScottPanIE` for you) :star2: this will acknowledge the removal of the branch :star2:
6. `git push ScottPanIE master` (this will update your fork with respect to `origin`)

The objective of this process, **which has to be repeated for every pull request**, is to be able to submit a second one without git problems.

~ If in doubt, please ask ~

:rainbow:

**Comment by ScottPanIE** [comment]
> ⚠️ Next steps ⚠️
> 
> Your pull request has been merged to `master`. That means that, if you don't do anything, your local `master` and `ScottPanIE/master` are outdated with respect to `origin/master`. On the other hand, you should avoid working on this branch anymore in the future.
> 
> To put yourself in a clean state again, you have to:
> 
>     1. Click "remove branch" here in this pull request (don't click "remove fork"!)
> 
>     2. `git checkout master`
> 
>     3. `git fetch origin` (assuming https://github.com/Juanlu001/ie-mbd-advanced-python/ is `origin` for you)
> 
>     4. `git merge --ff-only origin master` (this will update your local `master` with `origin/master`, and fail if you accidentally made any commit in `master`)
> 
>     5. `git fetch -p ScottPanIE` (assuming https://github.com/ScottPanIE/ie-mbd-advanced-python/ is `ScottPanIE` for you) 🌟 this will acknowledge the removal of the branch 🌟
> 
>     6. `git push ScottPanIE master` (this will update your fork with respect to `origin`)
> 
> 
> The objective of this process, **which has to be repeated for every pull request**, is to be able to submit a second one without git problems.
> 
> ~ If in doubt, please ask ~
> 
> 🌈

Thanks for guiding me through the issues !

**Pull request merged**
