### PR TITLE
GitHub practice - Duarte Afonso test

### PR DESCRIPTION
**Pull request by dartonso**

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Hi @dartonso! Can you confirm that your email <duarte.afonso@student.ie.edu> (which is correctly included in the commits) appears in your list of verified emails https://github.com/settings/emails? Seems like the commits are still not correctly attributed.

**Comment by dartonso** [comment]
> Hi @dartonso! Can you confirm that your email [duarte.afonso@student.ie.edu](mailto:duarte.afonso@student.ie.edu) (which is correctly included in the commits) appears in your list of verified emails https://github.com/settings/emails? Seems like the commits are still not correctly attributed.

Yes its my email. What you mean with this "Seems like the commits are still not correctly attributed."?

**Comment by astrojuanlu** [comment]
> Yes its my email. What you mean with this "Seems like the commits are still not correctly attributed."?

I mean that GitHub does not recognize them as connected to your GitHub account. In fact, you can see that the avatars are different:

Screenshot_2019-04-02 GitHub practice - Duarte Afonso test by dartonso · Pull Request #43 · Juanlu001 ie-mbd-advanced-python

I suspect that it's because you haven't verified your email in GitHub yet:

https://github.com/settings/emails

**Comment by dartonso** [comment]
> > Yes its my email. What you mean with this "Seems like the commits are still not correctly attributed."?
> 
> I mean that GitHub does not recognize them as connected to your GitHub account. In fact, you can see that the avatars are different:
> 
> Screenshot_2019-04-02 GitHub practice - Duarte Afonso test by dartonso · Pull Request #43 · Juanlu001 ie-mbd-advanced-python
> 
> I suspect that it's because you haven't verified your email in GitHub yet:
> 
> https://github.com/settings/emails

Ohh, i see. My email of github is not the one from IE. Ok, so i could change the email on the config file in git and recommit the file. That would work right?

**Comment by astrojuanlu** [comment]
But you don't need to recommit the file, because you can have several emails on GitHub, as many as you want. I think it's correct that you made your commits with your IE email, so adding it to your emails list should do the trick.

**Comment by dartonso** [comment]
> But you don't need to recommit the file, because you can have several emails on GitHub, as many as you want. I think it's correct that you made your commits with your IE email, so adding it to your emails list should do the trick.

just did it.
So because i was using an email non verified you couldn't merge the branch?

**Comment by astrojuanlu** [comment]
>  So because i was using an email non verified you couldn't merge the branch?

I could merge the branch, but I wanted to make sure we could fix the attribution before doing it, just in case :)

**Review by astrojuanlu — APPROVED** [review]

**Comment by astrojuanlu** [comment]
:warning: Next steps :warning: 

Your pull request has been merged to `master`. That means that, if you don't do anything, your local `master` and `dartonso/master` are outdated with respect to `origin/master`. On the other hand, you should avoid working on this branch anymore in the future.

To put yourself in a clean state again, you have to:

1. Click "remove branch" here in this pull request (don't click "remove fork"!)
2. `git checkout master`
3. `git fetch origin` (assuming https://github.com/Juanlu001/ie-mbd-advanced-python/ is `origin` for you)
4. `git merge --ff-only origin master` (this will update your local `master` with `origin/master`, and fail if you accidentally made any commit in `master`)
5. `git fetch -p dartonso` (assuming https://github.com/dartonso/ie-mbd-advanced-python/ is `dartonso` for you) :star2: this will acknowledge the removal of the branch :star2:
6. `git push dartonso master` (this will update your fork with respect to `origin`)

The objective of this process, **which has to be repeated for every pull request**, is to be able to submit a second one without git problems.

~ If in doubt, please ask ~

:rainbow:

**Pull request merged**
