### PR TITLE
cleliacrv.txt

### PR DESCRIPTION
**Pull request by cleliacrv**

### CODE REVIEW

**Review by astrojuanlu — COMMENTED** [review]
Awesome! I noticed that you created a pull request on your fork to your own branch:

https://github.com/cleliacrv/ie-mbd-advanced-python/pull/1

Was it your original intention? It's not a problem, but it deviates from the way people usually work. It also complicates a bit [the git graph](https://github.com/Juanlu001/ie-mbd-advanced-python/network):

Screenshot_2019-03-30 Juanlu001 ie-mbd-advanced-python

**Comment by cleliacrv** [comment]
> Awesome! I noticed that you created a pull request on your fork to your own branch:
> 
> [cleliacrv#1](https://github.com/cleliacrv/ie-mbd-advanced-python/pull/1)
> 
> Was it your original intention? It's not a problem, but it deviates from the way people usually work. It also complicates a bit [the git graph](https://github.com/Juanlu001/ie-mbd-advanced-python/network):

Originally I thought that by creating a branch in the fork and then pulling to the master, it would've pulled to the main repository. I realized I was wrong, and that I was pulling to the fork master rather than the main repository, so then used this work-around. I also helped Leon, so you'll see the same on his. 

Best, 
Clelia :)

**Comment by astrojuanlu** [comment]
No problem! Will merge anyways then :+1:

**Comment by astrojuanlu** [comment]
:warning: Next steps :warning: 

Your pull request has been merged to `master`. That means that, if you don't do anything, your local `master` and `cleliacrv/master` are outdated with respect to `origin/master`. On the other hand, you should avoid working on this branch anymore in the future.

To put yourself in a clean state again, you have to:

1. Click "remove branch" here in this pull request (don't click "remove fork"!)
2. `git checkout master`
3. `git fetch origin` (assuming https://github.com/Juanlu001/ie-mbd-advanced-python/ is `origin` for you)
4. `git merge --ff-only origin master` (this will update your local `master` with `origin/master`, and fail if you accidentally made any commit in `master`)
5. `git fetch -p cleliacrv` (assuming https://github.com/cleliacrv/ie-mbd-advanced-python/ is `cleliacrv` for you) :star2: this will acknowledge the removal of the branch :star2:
6. `git push cleliacrv master` (this will update your fork with respect to `origin`)

The objective of this process, **which has to be repeated for every pull request**, is to be able to submit a second one without git problems.

~ If in doubt, please ask ~

:rainbow:

**Comment by astrojuanlu** [comment]
Sorry, I noticed that my comment doesn't make sense because you didn't create a branch in the first place, sorry for the oversight.

In normal circumstances try to avoid committing to `master` directly, and always use a branch. Please try to run steps 3, 4 and 6, and ping me if any of those fail.

**Comment by cleliacrv** [comment]
I'm confused.. I did create a branch within my own fork: cleliacrv-banch-1. I understand the need to update my local master (the fork master that is, I assume) with the origin/master (your repository), but what this means to do is to also remove cleliacrv-banch-1 in the fork as well?

**Comment by astrojuanlu** [comment]
> I understand the need to update my local master (the fork master that is, I assume) with the origin/master (your repository)

Correct!

> to also remove cleliacrv-banch-1 in the fork as well?

Also correct.

**Comment by astrojuanlu** [comment]
> I understand the need to update my local master (the fork master that is, I assume) with the origin/master (your repository)

Correct!

> to also remove cleliacrv-banch-1 in the fork as well?

Also correct.

**Pull request merged**
